language: java   #Especificamos lenguaje
jdk:             # Y version de jdk
  -oraclejdk11
  

before_script:
  - cd imageCo
  - mvn clean

script:    # Indicamos la carpeta donde se situa el pom.xml y la compilacion y ejecución de los test con maven
  - mvn compile       
  - mvn test                #Se ejecutan los tests
  - mvn spring-boot:run
  
 after script:
  - mvn spring-boot:stop


